### PR TITLE
Finish up the repository

### PR DESCRIPTION
**Pull request by Simply007**
### Motivation

The repo was marked as a concept. I think we are ready to remove this mark.
@makma - Please go through the code/readme/issues if there is something to be adjusted/added.

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by Simply007** [comment]
Once merged - let @strizr know.

**Comment by makma** [comment]
## Readme
- `Use the Template Manager UI for importing the content from kontent-backup.zip file and API keys from previous step. Check Publish language variants after import option before import.` - import URL - page not found after onclick
- `Project contains data inconsistencies. You may proceed with import, but it is possible that import will fail.
` - why so? - using `kontent-backup.zip`
-  `if you don't have your PREVIEW_SECRET, your preview is not...` - I'd add a note it needs to be configured in the env variables
- I reckon the readme is too overloaded. Consider extracting  `About` , `Code`, `RTE resolution`, and `Desing` info

### Grammar, articles, typos
- articles: from **the** previous step, If you need **a** more complex setup,  from **the** data modeling point..., For **a** better idea ad more...
- To generate the site locally, **run fun** following command - this one is funny :D
- Content is **modelled** to be ready for being used...
- because this **starters** should also...
-  serve **to to** users
-  Remove **the the** "old" homep...
- This step **are** easily scriptable by
- the logic **in** centralized
- the specific depth and then traverse**s** down...
- proper component, it fails or display**s** ...
-  in case **od** development environment
- on-published content and the toolbar that allow**s** you to exit the preview.
- offers a possibility to set **te** preview
- This allows to **to** close the preview
- **netlify** plugin does
-  the site has to be **build**
- environment variable **is** set to true.

## App
- after running `npm run dev` in the console I got `Warning: Received 'true' for a non-boolean attribute 'crossOrigin'`.

## Otherwise great job

**Review by makma — APPROVED** [review]
## Readme
- `Use the Template Manager UI for importing the content from kontent-backup.zip file and API keys from previous step. Check Publish language variants after import option before import.` - import URL - page not found after onclick
- `Project contains data inconsistencies. You may proceed with import, but it is possible that import will fail.
` - why so? - using `kontent-backup.zip`
-  `if you don't have your PREVIEW_SECRET, your preview is not...` - I'd add a note it needs to be configured in the env variables
- I reckon the readme is too overloaded. Consider extracting  `About` , `Code`, `RTE resolution`, and `Desing` info

### Grammar, articles, typos
- articles: from **the** previous step, If you need **a** more complex setup,  from **the** data modeling point..., For **a** better idea ad more...
- To generate the site locally, **run fun** following command - this one is funny :D
- Content is **modelled** to be ready for being used...
- because this **starters** should also...
-  serve **to to** users
-  Remove **the the** "old" homep...
- This step **are** easily scriptable by
- the logic **in** centralized
- the specific depth and then traverse**s** down...
- proper component, it fails or display**s** ...
-  in case **od** development environment
- on-published content and the toolbar that allow**s** you to exit the preview.
- offers a possibility to set **te** preview
- This allows to **to** close the preview
- **netlify** plugin does
-  the site has to be **build**
- environment variable **is** set to true.

## App
- after running `npm run dev` in the console I got `Warning: Received 'true' for a non-boolean attribute 'crossOrigin'`.

## Otherwise great job

**Comment by Simply007** [comment]
> ## Readme
> * `Use the Template Manager UI for importing the content from kontent-backup.zip file and API keys from previous step. Check Publish language variants after import option before import.` - import URL - page not found after onclick
* Related to https://github.com/Kentico/kontent-template-manager/issues/56 > fix in https://github.com/Kentico/kontent-template-manager/pull/61 and quick fix in https://github.com/Kentico/kontent-template-manager/commit/e84289df1239cb7f4e72b9fcd442b511f9c05fbb
> * `Project contains data inconsistencies. You may proceed with import, but it is possible that import will fail. ` - why so? - using `kontent-backup.zip`
* There is an item with the required field not set (Unfinished blogpost for preview testing purposes) - I have removed it and export the site again - done in a563e85
> * `if you don't have your PREVIEW_SECRET, your preview is not...` - I'd add a note it needs to be configured in the env variables
* Done in 9ead32c
> * I reckon the readme is too overloaded. Consider extracting  `About` , `Code`, `RTE resolution`, and `Desing` info


> ### Grammar, articles, typos

* Done in ae9248c

> ## App
> * after running `npm run dev` in the console I got `Warning: Received 'true' for a non-boolean attribute 'crossOrigin'`.
> 
> ## Otherwise great job

**Review by makma — APPROVED** [review]
Works and looks great, thank you for the changes

**Pull request merged**
